#!/bin/bash
# ================================================================
#  AI Stack Launcher — Intel Arc A770 / llama.cpp SYCL
#  Generated by install.sh — edit lib/config.sh then re-run
#  write_startup_script() to regenerate.
# ================================================================

source "$HOME/.cargo/env" 2>/dev/null || true
[ -f /opt/intel/oneapi/setvars.sh ] \
    && source /opt/intel/oneapi/setvars.sh --force >/dev/null 2>&1

export ONEAPI_DEVICE_SELECTOR="level_zero:0"
export SYCL_DEVICE_FILTER="level_zero:gpu"
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

LLAMA_SERVER="{{LLAMACPP_BIN}}"
MODEL="{{MODEL_PATH}}"
LOGS="{{LOG_DIR}}"
mkdir -p "$LOGS"

echo "🤖 Starting AI Stack (Intel Arc A770 / llama.cpp SYCL)…"

"$LLAMA_SERVER" \
    --model       "$MODEL" \
    --ctx-size    {{LLAMA_CTX_SIZE}} \
    --n-gpu-layers {{LLAMA_GPU_LAYERS}} \
    --port        {{LLAMA_PORT}} \
    --host        {{LLAMA_HOST}} \
    --api-key     {{LLAMA_API_KEY}} \
    > "$LOGS/engine.log" 2>&1 &

ENGINE_PID=$!
echo "$ENGINE_PID" > "{{INSTALL_DIR}}/.pids"
echo "  ⏳ Engine PID $ENGINE_PID — waiting for API…"

for i in $(seq 1 90); do
    sleep 1
    curl -sf http://localhost:{{LLAMA_PORT}}/v1/models >/dev/null 2>&1 && break
done

if curl -sf http://localhost:{{LLAMA_PORT}}/v1/models >/dev/null 2>&1; then
    echo "  ✅ Engine ready."
else
    echo "  ❌ Engine failed to start — check $LOGS/engine.log"
    kill "$ENGINE_PID" 2>/dev/null || true
    exit 1
fi

command -v anythingllm &>/dev/null \
    && { anythingllm &>/dev/null & echo "  ✅ AnythingLLM launched."; }

echo ""
echo "🚀 Stack LIVE — API: http://localhost:{{LLAMA_PORT}}"
echo "   Logs : $LOGS/"
echo "   Stop : kill \$(cat {{INSTALL_DIR}}/.pids)"
