#!/bin/bash
# ================================================================
#  AI Stack Uninstaller
#  Generated by install.sh — do not edit directly.
# ================================================================
set -euo pipefail

INSTALL_DIR="{{INSTALL_DIR}}"
MODEL_DIR="{{MODEL_DIR}}"

echo "🧹 AI Stack Uninstaller"
echo ""

if [[ ! -d "$INSTALL_DIR" ]]; then
    echo "Nothing to uninstall — $INSTALL_DIR not found."
    exit 0
fi

read -rp "Remove downloaded models as well? [y/N]: " rm_models
rm_models="${rm_models:-n}"

echo ""
echo "Removing core stack…"

if [[ -d "$INSTALL_DIR" ]]; then
    find "$INSTALL_DIR" -mindepth 1 -maxdepth 1 ! -name models -exec rm -rf {} +
fi

if [[ "${rm_models,,}" == "y" ]]; then
    echo "Removing models…"
    rm -rf "$MODEL_DIR"
else
    echo "Keeping models at: $MODEL_DIR"
fi

rm -f "$HOME/.local/bin/anythingllm" 2>/dev/null || true
rm -f "$HOME/.local/share/applications/anythingllm.desktop" 2>/dev/null || true
rm -f "$HOME/uninstall_ai_stack.sh" 2>/dev/null || true

echo ""
echo "✅ Uninstall complete."
[[ "${rm_models,,}" != "y" ]] && echo "📦 Models retained at: $MODEL_DIR"
